version: "3.8"

services:
  z2api:
    image: ghcr.io/songonroc/z2api:latest
    container_name: z2api
    ports:
      - "${PORT:-9090}:9090"
    environment:
      - DEFAULT_KEY=${DEFAULT_KEY:-sk-123456}
      - ZAI_TOKEN=${ZAI_TOKEN}
      - MODEL_NAME=${MODEL_NAME:-GLM-4.5}
      - PORT=${PORT:-9090}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - DEFAULT_STREAM=${DEFAULT_STREAM:-true}
      - DASHBOARD_ENABLED=${DASHBOARD_ENABLED:-true}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9090/docs",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
